config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'about/how'
  root 'about#home'

  devise_for :users

  resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :goals do
    resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :users, only: [:show]

  resources :users do
    resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :about, only: [:index, :home]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :user, presence: true
  validates :name, presence: true
  validates :duration, presence: true
  validates :name, length: { maximum: 100 }
  validates :objective, length: { maximum: 255}
  validates_numericality_of :duration, greater_than: 0
  validates_inclusion_of :completed, in: [true, false]
  validates_inclusion_of :secret, in: [true, false]

  def self.authorized_find(user, id)
    if user.admin?
      find(id)
    else
      where(user: user).find(id)
    end
  end

  def self.ideal_allocation
    {study: 0.1, drill: 0.25, do: 0.65}
  end

  def ideal_allocation
    allocation = {study: ((duration * Goal.ideal_allocation[:study]).to_i),
                  drill: ((duration * Goal.ideal_allocation[:drill]).to_i),
                  do: ((duration * Goal.ideal_allocation[:do]).to_i)
                  }
  end

  def actual_allocation
    alloc = {study: 0, drill: 0, do: 0}

    tasks.each do |task|
      if task.methodology.name == "study"
        alloc[:study] += task.duration
      elsif task.methodology.name == "drill"
         alloc[:drill] += task.duration
      else
        alloc[:do] += task.duration
      end
    end
    alloc
  end

  def actual_array
    actual_array = []
    self.actual_allocation.each do |k, v|
      actual_array << [k.to_s, v]
    end
    actual_array
  end

  def ideal_array
    ideal_array = []
    self.ideal_allocation.each do |k, v|
      ideal_array << [k.to_s, v]
    end
    ideal_array
  end

  def ongoing_array
    ongoing_array = []
    elapsed_time = 0
    self.actual_allocation.each do |k, v|
      ongoing_array << [k.to_s, v]
      elapsed_time += v
    end
    t_remaining = (duration  - elapsed_time)
    ongoing_array << ["time remaining", t_remaining]
    ongoing_array
  end

  def elapsed_time
    tot_time = 0
    goal.tasks.each do |task|
        tot_time += task.duration
    end
    tot_time
  end

  def advice_calc(ideal, actual)
    advice = []

    ideal.each do |k, v|
      if v > actual[k]
        advice << "<div id=\"noneyet\">Not Enough</div>".html_safe
      elsif v < actual[k]
        advice << "<div id=\"offtrack\">Too much</div>".html_safe
      else
        advice << "<div id=\"ontrack\">Just Right</div>".html_safe
      end
    end
    advice
  end

  def ontrack?(ideal, actual)
    ontrack = []
    actual.each do |k, v|
      if v == 0
        ontrack << "<div id=\"noneyet\">None Yet</div>".html_safe
      elsif v == ideal[k]
        ontrack << "<div id=\"ontrack\">On Track</div>".html_safe
      else
        ontrack << "<div id=\"offtrack\">Off Track</div>".html_safe
      end
    end
    ontrack
  end

  def editable_by?(user)
    self.user == user || user.admin?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: [:edit, :update, :destroy]

  def index
    @goals = Goal.where(secret: false).order(created_at: :desc).includes(:user)
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    if @goal.save
      redirect_to @goal
      flash[:notice] = "Your goal has successfully been set!"
    else
      flash[:alert] = "There was a problem, please try again."
      render :new
    end
  end

  def show
    @goal = Goal.includes(:user, :tasks).find(params[:id])
    @user_image = @goal.user.profile_photo.thumb
    @my_allocation = @goal.actual_allocation
    @best_allocation = @goal.ideal_allocation
    gon.ideal_pie = @goal.ideal_array
    gon.actual_pie = @goal.actual_array
    gon.ongoing_pie = @goal.ongoing_array
    @advice = @goal.advice_calc(@best_allocation, @my_allocation)
    @ontrack = @goal.ontrack?(@best_allocation, @my_allocation)
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    if @goal.update(goal_params)
      flash[:notice] = "Goal Updated"
      redirect_to goal_path
    else
      flash[:notice] = "There was a problem, please try again."
      render :edit
    end
  end

  def destroy
    if @goal.destroy
      flash[:notice] = "Goal Deleted"
      redirect_to goals_path
    else
      flash[:alert] = "There was a problem, please try again."
      render :edit
    end
  end

  private

  def set_goal
      @goal = Goal.authorized_find(current_user, params[:id])
  end

  def goal_params
    params.require(:goal).permit(:name, :duration, :completed, :objective, :secret, :user_id)
  end

  def authorize_user
    unless user_signed_in? and current_user.admin?
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/views/goals/_allocation.html.erb
<tr>
  <th>Method</th>
  <th>Ideal Time</th>
  <th>My Time</th>
  <th>Recommendation</th>
</tr>
<tr>
  <td>Study</td>
  <td><%= @best_allocation[:study] %> minutes </td>
  <td><%= @my_allocation[:study] %> minutes </td>
  <td><%= @advice[0] %> </td>
</tr>
<tr>
  <td>Drill</td>
  <td><%= @best_allocation[:drill] %> minutes </td>
  <td><%= @my_allocation[:drill] %> minutes </td>
  <td><%= @advice[1] %></td>
</tr>
<tr>
  <td>Do</td>
  <td><%= @best_allocation[:do] %> minutes </td>
  <td><%= @my_allocation[:do] %> minutes </td>
  <td><%= @advice[2] %></td>
</tr>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
<% if @goal.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being submitted:</h3>

    <ul>
    <% @goal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :name, "Goal" %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :duration_in_minutes %>
  <%= f.text_field :duration %>
</p>

<p>
  <%= f.label :completed, "Finished?" %>
  <%= f.radio_button :completed, true %><label for="completed_true">yes</label>
  <%= f.radio_button :completed, false %><label for="completed_false">not yet</label>
</p>

<p>
  <%= f.label :objective%><br>
  <%= f.text_area :objective %>
</p>

<p>
  <%= f.check_box :secret %>
  <%= f.label :secret, "Make this goal private" %>
</p>

<p>
  <%= f.submit class: 'button radius' %>
</p>
<% end %>

app/views/goals/edit.html.erb
<h1>Revise A Goal</h1>

<%= render 'form' %>

<p><%= link_to 'Delete', @goal, class: 'button radius', method: :delete, data: { confirm: 'Are you sure you want to delete this goal?' } %></p>
<p><%= link_to 'Back to Goal', goal_path(@goal) %></p>

app/views/goals/index.html.erb
<h1>Goals</h1>
<p><%= link_to "Set Your Own Goal", new_goal_path, class: 'button radius' %></p>

<div class="goals_index"
<ul>
    <% @goals.each do |goal| %>
      <li><div id="user-thumb"><%= image_tag(goal.user.profile_photo.thumb) %></div>
      <%= link_to goal.name, goal_path(goal) %> |
      Set on: <%= format_datetime(goal.created_at)%>
      by <%= link_to goal.user.username, user_path(goal.user) %> |
      <%= completed(goal) %>
      <% end %></li>
  </ul>
</div>

app/views/goals/new.html.erb
<h1>Set a Goal</h1>
<div class="form">
<%= render 'form' %>
</div>

app/views/goals/show.html.erb
<div class="box2">
<div id="user-thumb"><%= image_tag(@goal.user.profile_photo.thumb) %><%= link_to @goal.user.username, user_path(@goal.user) %></div>
<h1>Goal: <%= @goal.name %></h1>

  <div>
    <%= private(@goal) %>
    <%= completed_flag(@goal) %>
    <% if @goal.editable_by?(current_user) %>
    <%= link_to "Revise", edit_user_goal_path(@goal.user, @goal) %> | <%= link_to 'Delete', @goal, method: :delete, data: { confirm: 'Are you sure you want to delete this goal?' } %><% end %><br><br>
  </div>
  <strong>Date Set: </strong><%= format_datetime(@goal.created_at)%><br>
  <strong>Duration: </strong><%= format_duration(@goal.duration)%><br>
  <% if @goal.objective %>
    <strong> Objective </strong>
    <%= @goal.objective %>
  <% end %>
  <br>
</div>

<div class="box3">
  <% if !@goal.tasks.empty? %>
    <h2>Steps towards this goal</h2>
    <% if @goal.user == current_user %>
      <%= link_to "Take a Step", new_goal_task_path(@goal) %>
    <% end %>
    <ul>
      <% @goal.tasks.each do |task| %>
        <li>
          <% if task.secret %>
           <div class="private-bullet">P</div><%= link_to task.focus, task_path(task) %> | <%= format_datetime(task.created_at)%>
          <% else %>
            <%= link_to task.focus, task_path(task) %> |  <%= format_datetime(task.created_at)%>
          <% end%>
        </li>
        <% end %>
    </ul>
  <% elsif @goal.user == current_user %>
    <p>Get started towards this goal by <%= link_to "adding a task", new_goal_task_path(@goal) %>. </p>
  <% end %>
</div>

<% if @goal.completed %>
  <div class="allocation">
  <h3>study.drill.do assessment</h3>
    <table>
      <tr>
        <th>Method</th>
        <th>Ideal Time</th>
        <th>My Time</th>
        <th>Status</th>
      </tr>
      <tr>
        <td>Study</td>
        <td><%= @best_allocation[:study] %> minutes </td>
        <td><%= @my_allocation[:study] %> minutes </td>
        <td><%= @advice[0] %> </td>
      </tr>
      <tr>
        <td>Drill</td>
        <td><%= @best_allocation[:drill] %> minutes </td>
        <td><%= @my_allocation[:drill] %> minutes </td>
        <td><%= @advice[1] %></td>
      </tr>
      <tr>
        <td>Do</td>
        <td><%= @best_allocation[:do] %> minutes </td>
        <td><%= @my_allocation[:do] %> minutes </td>
        <td><%= @advice[2] %></td>
      </tr>
    </table>
  </div>

  <div class="pie_charts">
    <div id="ideal_pie"></div>
    <div id="actual_pie"></div>
  </div>

<% else %>
<div class="ongoing_container">
 <div id="ongoing_table">
  <h3>study.drill.do assessment</h3>
  <table>
    <tr>
      <th>Method</th>
      <th>Ideal Time</th>
      <th>My Time</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>Study</td>
      <td><%= @best_allocation[:study] %> minutes </td>
      <td><%= @my_allocation[:study] %> minutes </td>
      <td><%= @ontrack[0] %></td>
    </tr>
    <tr>
      <td>Drill</td>
      <td><%= @best_allocation[:drill] %> minutes </td>
      <td><%= @my_allocation[:drill] %> minutes </td>
      <td><%= @ontrack[1] %></td>
    </tr>
    <tr>
      <td>Do</td>
      <td><%= @best_allocation[:do] %> minutes </td>
      <td><%= @my_allocation[:do] %> minutes </td>
      <td><%= @ontrack[2] %></td>
    </tr>
  </table>
  </div>

  <div id="ongoing_pie"></div>
</div>
<% end %>