config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'about/how'
  root 'about#home'

  devise_for :users

  resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :goals do
    resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :users, only: [:show]

  resources :users do
    resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :about, only: [:index, :home]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :username, presence: true
  validate :email_valid

  # Other available devise modules :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def email_valid
    unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      errors[:base] << "Please enter a valid email."
    end
  end

  def admin?
    role == 'admin'
  end

  def is_admin?
    role == 'admin'
  end

  mount_uploader :profile_photo, ProfilePhotoUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_filter :authorize!
  def index
    @users = User.order(created_at: :desc)
    @admins = @users.where(role: "admin")
    @members = @users.where(role: "member")
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "User successfully deleted."
    else
      flash[:alert] = "Could not delete the user."
    end

    redirect_to admin_users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user_goals = @user.goals.order(created_at: :desc)
    @user_tasks = @user.tasks.order(created_at: :desc)
  end
end

app/views/admin/users/index.html.erb
<div class="container">
<h2>Admin Users</h2>
<ul>
  <% @admins.each do |admin| %>
    <li>
      <%= link_to admin.username, user_path(admin) %> | <%= admin.email %> | Created: <%= admin.created_at.strftime('%b %d, %Y') %> | Profile last updated: <%= admin.created_at.strftime('%b %d, %Y') %>
    </li>
  <% end %>
  </ul>

<h2>Regular Users</h2>
<ul>
  <% @members.each do |member| %>
    <li>
      <%= link_to member.username, user_path(member) %> | <%= member.email %> | Created: <%= member.created_at.strftime('%b %d, %Y') %> | Profile last updated: <%= member.created_at.strftime('%b %d, %Y') %> | <%= link_to 'Delete', admin_user_path(member), method: :delete, data: { confirm: 'Do you really want to delete this user?' }%>
    </li>
  <% end %>
  </ul>
</div>