config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'about/how'
  root 'about#home'

  devise_for :users

  resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :goals do
    resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  resources :tasks, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  resources :users, only: [:show]

  resources :users do
    resources :goals, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :about, only: [:index, :home]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>study.drill.do</title>
  <%= include_gon %>
  <%= stylesheet_link_tag "application", media: "all"  %>
  <link href='//fonts.googleapis.com/css?family=Lato:400,400italic|Lora|Neucha' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<div class="nav">
  <div class="logo">
    <a href="/">study.drill.do</a>
  </div>
  <ul>
    <li>
      <%= link_to "All Goals", goals_path, class: 'button radius' %>
    </li>
  <% if user_signed_in? %>
      <li>
      <%= link_to 'Me & My Goals', user_path(current_user), class: 'button radius' %>
      </li>
  <% end %>
    <li>
      <%= link_to 'Set a Goal', new_goal_path, class: 'button radius' %>
    </li>

    <% if user_signed_in? %>
      <li>
      <%= link_to('Sign Out', destroy_user_session_path, class: 'button radius', method: :delete) %>
      </li>
    <% else %>
      <li>
      <%= link_to('Login', new_user_session_path, class: 'button radius') %>
      </li>
    <% end %>

    <% if user_signed_in? && current_user.admin? %>
      <li>
        <%= link_to 'Admin', admin_users_path, class: 'button radius' %>
      </li>
    <% end %>
    <li>
      <%= link_to 'How It Works', about_how_path, class: 'button radius' %>
    </li>
    <li>
      <%= link_to 'About', about_index_path, class: 'button radius' %>
    </li>
  </ul>
</div>

<div class="clear-container">
  <% if !notice.nil? %><p class="alert-box radius success"><%= notice %></p><% end %>
  <% if !alert.nil? %><p class="alert-box radius warning"><%= alert %></p><% end %>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>